# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\06LogicPi\04Git_Projects\SerialMaster\main.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(864, 645)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/串口.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 99))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_SendCnt = QtWidgets.QLabel(self.groupBox_3)
        self.label_SendCnt.setFrameShape(QtWidgets.QFrame.Box)
        self.label_SendCnt.setText("")
        self.label_SendCnt.setObjectName("label_SendCnt")
        self.gridLayout_4.addWidget(self.label_SendCnt, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 1)
        self.pushButton_SendClearCnt = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_SendClearCnt.setObjectName("pushButton_SendClearCnt")
        self.gridLayout_4.addWidget(self.pushButton_SendClearCnt, 2, 1, 1, 1)
        self.checkBox_SendHEX = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_SendHEX.setObjectName("checkBox_SendHEX")
        self.gridLayout_4.addWidget(self.checkBox_SendHEX, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 143))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_ReceiveClearCnt = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_ReceiveClearCnt.setObjectName("pushButton_ReceiveClearCnt")
        self.gridLayout_3.addWidget(self.pushButton_ReceiveClearCnt, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 4, 0, 1, 1)
        self.checkBox_ReceiveShowTime = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_ReceiveShowTime.setObjectName("checkBox_ReceiveShowTime")
        self.gridLayout_3.addWidget(self.checkBox_ReceiveShowTime, 2, 1, 1, 1)
        self.checkBox_ReceiveHEX = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_ReceiveHEX.setObjectName("checkBox_ReceiveHEX")
        self.gridLayout_3.addWidget(self.checkBox_ReceiveHEX, 0, 1, 1, 1)
        self.label_ReceiveCnt = QtWidgets.QLabel(self.groupBox_2)
        self.label_ReceiveCnt.setFrameShape(QtWidgets.QFrame.Box)
        self.label_ReceiveCnt.setText("")
        self.label_ReceiveCnt.setObjectName("label_ReceiveCnt")
        self.gridLayout_3.addWidget(self.label_ReceiveCnt, 4, 1, 1, 1)
        self.checkBox_ReceiveAutoNewLine = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_ReceiveAutoNewLine.setObjectName("checkBox_ReceiveAutoNewLine")
        self.gridLayout_3.addWidget(self.checkBox_ReceiveAutoNewLine, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(240, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_FlowCtrl = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_FlowCtrl.setObjectName("comboBox_FlowCtrl")
        self.comboBox_FlowCtrl.addItem("")
        self.gridLayout.addWidget(self.comboBox_FlowCtrl, 6, 1, 1, 1)
        self.comboBox_BaundRate = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_BaundRate.setEditable(True)
        self.comboBox_BaundRate.setObjectName("comboBox_BaundRate")
        self.comboBox_BaundRate.addItem("")
        self.comboBox_BaundRate.addItem("")
        self.comboBox_BaundRate.addItem("")
        self.comboBox_BaundRate.addItem("")
        self.gridLayout.addWidget(self.comboBox_BaundRate, 2, 1, 1, 1)
        self.comboBox_StopBit = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_StopBit.setObjectName("comboBox_StopBit")
        self.comboBox_StopBit.addItem("")
        self.gridLayout.addWidget(self.comboBox_StopBit, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.comboBox_Port = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_Port.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_Port.setObjectName("comboBox_Port")
        self.gridLayout.addWidget(self.comboBox_Port, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.comboBox_DataLen = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_DataLen.setObjectName("comboBox_DataLen")
        self.comboBox_DataLen.addItem("")
        self.gridLayout.addWidget(self.comboBox_DataLen, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.comboBox_CheckSum = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_CheckSum.setObjectName("comboBox_CheckSum")
        self.comboBox_CheckSum.addItem("")
        self.gridLayout.addWidget(self.comboBox_CheckSum, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.pushButton_Open = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Open.setObjectName("pushButton_Open")
        self.gridLayout.addWidget(self.pushButton_Open, 7, 1, 1, 1)
        self.pushButton_RefreshPort = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_RefreshPort.setObjectName("pushButton_RefreshPort")
        self.gridLayout.addWidget(self.pushButton_RefreshPort, 7, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 2, 1)
        self.textEdit_Receive = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit_Receive.setMinimumSize(QtCore.QSize(600, 0))
        self.textEdit_Receive.setObjectName("textEdit_Receive")
        self.gridLayout_2.addWidget(self.textEdit_Receive, 0, 1, 4, 2)
        self.textEdit_Send = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit_Send.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textEdit_Send.setObjectName("textEdit_Send")
        self.gridLayout_2.addWidget(self.textEdit_Send, 4, 1, 1, 1)
        self.pushButton_Send = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Send.setObjectName("pushButton_Send")
        self.gridLayout_2.addWidget(self.pushButton_Send, 4, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 864, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menuBar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menuBar)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionDrawCurve = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/曲线.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDrawCurve.setIcon(icon1)
        self.actionDrawCurve.setObjectName("actionDrawCurve")
        self.actionSetting = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/设 置.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSetting.setIcon(icon2)
        self.actionSetting.setObjectName("actionSetting")
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.menuBar.addAction(self.menu_4.menuAction())
        self.menuBar.addAction(self.menu_5.menuAction())
        self.toolBar.addAction(self.actionDrawCurve)
        self.toolBar.addAction(self.actionSetting)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SerialMaster"))
        self.groupBox_3.setTitle(_translate("MainWindow", "发送设置"))
        self.label_9.setText(_translate("MainWindow", "发送计数："))
        self.pushButton_SendClearCnt.setText(_translate("MainWindow", "清空"))
        self.checkBox_SendHEX.setText(_translate("MainWindow", "十六进制"))
        self.groupBox_2.setTitle(_translate("MainWindow", "接收设置"))
        self.pushButton_ReceiveClearCnt.setText(_translate("MainWindow", "清空"))
        self.label_7.setText(_translate("MainWindow", "接收计数："))
        self.checkBox_ReceiveShowTime.setText(_translate("MainWindow", "显示时间"))
        self.checkBox_ReceiveHEX.setText(_translate("MainWindow", "十六进制"))
        self.checkBox_ReceiveAutoNewLine.setText(_translate("MainWindow", "自动换行"))
        self.groupBox.setTitle(_translate("MainWindow", "串口设置"))
        self.comboBox_FlowCtrl.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_BaundRate.setItemText(0, _translate("MainWindow", "9600"))
        self.comboBox_BaundRate.setItemText(1, _translate("MainWindow", "19200"))
        self.comboBox_BaundRate.setItemText(2, _translate("MainWindow", "38400"))
        self.comboBox_BaundRate.setItemText(3, _translate("MainWindow", "115200"))
        self.comboBox_StopBit.setItemText(0, _translate("MainWindow", "1"))
        self.label_3.setText(_translate("MainWindow", "数据位"))
        self.label_4.setText(_translate("MainWindow", "校验位"))
        self.comboBox_DataLen.setItemText(0, _translate("MainWindow", "8"))
        self.label_5.setText(_translate("MainWindow", "停止位"))
        self.label_6.setText(_translate("MainWindow", "流  控"))
        self.comboBox_CheckSum.setItemText(0, _translate("MainWindow", "None"))
        self.label.setText(_translate("MainWindow", "端  口"))
        self.label_2.setText(_translate("MainWindow", "波特率"))
        self.pushButton_Open.setText(_translate("MainWindow", "打开"))
        self.pushButton_RefreshPort.setText(_translate("MainWindow", "刷新"))
        self.pushButton_Send.setText(_translate("MainWindow", "发送"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.menu_3.setTitle(_translate("MainWindow", "视图"))
        self.menu_4.setTitle(_translate("MainWindow", "工具"))
        self.menu_5.setTitle(_translate("MainWindow", "帮助"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionDrawCurve.setText(_translate("MainWindow", "DrawCurve"))
        self.actionSetting.setText(_translate("MainWindow", "Setting"))

import source_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

